### PR TITLE
Fix problem with lowercased config map variables

### PR DESCRIPTION
**Pull request by c35sys**

### CODE REVIEW

**Comment by c35sys** [comment]
Issue #7

**Comment by pablo-ruth** [comment]
I think it will be better to change back-end interfaces to pass a sub viper object directly instead of a serialized map of string, so we can use viper methods to get values because it will abstract case problems for us. I pushed an example in subconfigViper branch (https://github.com/signmykeyio/signmykey/compare/subconfigViper). Config options in this example are in snake case but we can keep camel case notation.

**Comment by pablo-ruth** [comment]
Close in favor of #9

**Comment by pablo-ruth** [comment]
Close in favor of #9

**Pull request closed without merging**
