### PR TITLE
Optional OTP for local authenticator

### PR DESCRIPTION
**Pull request by cyber-anon**
The implementation extends the local authenticator with the option to use (T)OTP codes.
It should be backwards compatible and both otp-enabled and non-otp-enabled accounts are supported at the same time.

There are no additional security threats with this implementation.
Nevertheless, if someone has access to the server.yml file, one can remove the OTP requirement.
But then, of course, they can change the password altogether beyond just removing the OTP so this is an inherent existing threat and not a new one.

Parts of the code derived from https://github.com/pquerna/otp/ (Apache License 2.0)

### CODE REVIEW

**Comment by pablo-ruth** [comment]
Hello @cyber-anon, thanks for submitting this PR. I like your idea to add OTP to signmykey! I tested your PR and it works well. After reviewing the code I'm just a bit concerned about GenerateOTPCode function. I think I don't understand it well enough to maintain it in the future. Do you think it's possible to directly use pquerna/otp library for the OTP operations?

**Comment by cyber-anon** [comment]
I'm not a big fan of bloat, so I didn't bring a library in for just 10 lines of code function.  Using pquerna/otp would of course add the opportunity for HOTP support too, as well as other hashing algorithms. Using these though would require significantly more changes in signmykey so unless they are used, they just add to the attack surface.  

The function GenerateOTPCode, is derived from pquerna to make sure that golang is ok, but the function itself and calculation (lines 123-129 which I assume are the source of concern) is defined in the RFC (https://www.rfc-editor.org/rfc/rfc6238) in Java. The chances of this needing any kind of maintenance are quite slim. 

Having said that, pquerna's library is well documented and someone can replace the functions GenerateOTPCode, ProvisionURI, and GenerateSeed with calls to this library, with some modifications.

**Comment by pablo-ruth** [comment]
Sorry @cyber-anon  for the delay, I'm a bit busy this days. I get your point and I'm ok to not embed the OTP module. We can still switch to it in the future if needed.
So I'm ok to merge your PR, but before can you fix the golang-ci alerts and push updated go.mod file?

**Comment by cyber-anon** [comment]
> Sorry @cyber-anon for the delay, I'm a bit busy this days. I get your point and I'm ok to not embed the OTP module. We can still switch to it in the future if needed. So I'm ok to merge your PR, but before can you fix the golang-ci alerts and push updated go.mod file?

It should be better now.

**Comment by pablo-ruth** [comment]
Thanks for your contribution !

**Pull request merged**
